[build]
  command = "npm run build"
  publish = "dist"

[dev]
  command = "npm run dev"
  port    = 3000

# use Netlify's default functions dir:
[functions]
  directory = ".netlify/functions-internal"

# SSR catch-all
[[redirects]]
  from   = "/*"
  to     = "/.netlify/functions-internal/entry"
  status = 200

# optional: a pretty "/ â†’ /home" redirect
[[redirects]]
  from   = "/"
  to     = "/home"
  status = 302
